language: php

php:
  - 5.5
  - 5.6
  - 7

sudo: false

before_install:
  - composer self-update

install:
  - composer -n install

branches:
  only:
  - master

script: ./vendor/bin/phpunit -c tests/phpunit.xml
